Add API for manipulating Git hooks
go-gitea/go-sdk pull request #156
Opened 2019-03-26 14:20 UTC by segevfiner

This adds API support for manipulating Git hooks. Accompanying PR for a PR against Gitea.

2019-03-26 22:12 UTC, zeripath approved these changes

2019-03-26 22:17 UTC, zeripath requested changes

2019-03-26 22:17 UTC, zeripath commented on gitea/git_hook.go
> +	return hooks, c.getParsedResponse("GET", fmt.Sprintf("/repos/%s/%s/hooks/git", user, repo), nil, nil, &hooks)
It would generally be a good idea to PathEscape the user and repo here

2019-03-26 22:17 UTC, zeripath commented on gitea/git_hook.go
> +	return h, c.getParsedResponse("GET", fmt.Sprintf("/repos/%s/%s/hooks/git/%s", user, repo, id), nil, nil, h)
Please pathescape the user and repo and consider if id should be PathEscaped or PathSegmentsEscape

2019-03-26 22:17 UTC, zeripath commented on gitea/git_hook.go
> +	_, err = c.getResponse("PATCH", fmt.Sprintf("/repos/%s/%s/hooks/git/%s", user, repo, id), jsonHeader, bytes.NewReader(body))
Similarly

2019-03-26 22:17 UTC, zeripath commented on gitea/git_hook.go
> +	_, err := c.getResponse("DELETE", fmt.Sprintf("/repos/%s/%s/hooks/git/%s", user, repo, id), nil, nil)
Similarly

2019-03-26 23:15 UTC, segevfiner commented
@zeripath I based this on the existing API for web hooks, which doesn't seem to escape. Actually, I'm not seeing any reference to `PathEscape` in the entire SDK. So if I add escaping here, that will be the only place in the SDK that this would be done. So are you sure you want me to do this in this PR?

I couldn't find a function named `PathSegmentsEscape`, but should we add escaping here, we only need the normal `PathEscape` anyhow, as it's just the name of the hook which is a simple string without slashes.

P.S. If you are already looking at escaping URL components. An alternative way to build URLs with correct escaping is to use a library/package that implements [RFC 6570 - URI Template](https://tools.ietf.org/html/rfc6570) level 4 to build the URLs which already handles escaping and should interface quite nicely with a project that uses Swagger (Swagger/OpenAPI v3 was actually designed with it in mind).

2019-03-27 07:17 UTC, zeripath commented
We have to start somewhere. But I guess we'll have to do a refactor to actually escape all this stuff properly.

In terms of using templates to build URIs I suspect that any code that uses this will be bulky and verbose. Go doesn't have named function arguments, so you're then suggesting passing in either structs or maps to get the named arguments. Of course you can just use the go html template but even then you're probably going to end up with bulky code and you still have to pass in named arguments as a map or use numeric arguments.

Now there is an alternative and that is to get swagger or something else to generate this for us - this would clearly be the best idea but again that's a massive refactor. (I'm perfectly happy with bulky code so long as I never need look at it.)

Ok if you don't want to do the escaping I will approve but it really does need fixing - it doesn't exactly engender confidence in our code to see obvious escaping errors.

2019-03-27 07:17 UTC, zeripath approved these changes

2019-04-16 17:28 UTC, techknowlogick approved these changes

2019-04-16 17:28 UTC, merged