Functions for Collaborators
go-gitea/go-sdk pull request #27
Opened 2016-12-13 02:01 UTC by ethantkoenig

Add functions corresponding to the following endpoints:
- `GET repos/:username/:reponame/collaborators`: list collaborators
- `GET repos/:username/:reponame/collaborators/:collaborator`: check if a user is a collaborator
- `DELETE repos/:username/:reponame/collaborators/:collaborator`: remove a collaborator

These endpoints are implemented in https://github.com/go-gitea/gitea/pull/375.

2016-12-13 05:14 UTC, bkcsoft commented
LGTM

2016-12-13 05:28 UTC, lunny requested changes

2016-12-13 05:28 UTC, lunny commented on gitea/repo_collaborator.go
> +func (c *Client) ListCollaborators(user, repo string) ([]*User, error) {
pager?

2016-12-19 19:18 UTC, bkcsoft commented on gitea/repo_collaborator.go
> +func (c *Client) ListCollaborators(user, repo string) ([]*User, error) {
this needs pagination yes, I must've missed that one 🙁

2016-12-19 19:32 UTC, tboerger commented on gitea/repo_collaborator.go
> +func (c *Client) ListCollaborators(user, repo string) ([]*User, error) {
IMHO pager makes only sense for potentially large lists

2016-12-20 01:13 UTC, lunny requested changes

2016-12-20 01:13 UTC, lunny commented on gitea/repo_collaborator.go
> +	collaborators := make([]*User, 10)
```collaborators := make([]*User, 0, 10)```

2016-12-20 01:13 UTC, lunny commented on gitea/repo_collaborator.go
> +func (c *Client) ListCollaborators(user, repo string) ([]*User, error) {
That's OKay.

2016-12-20 06:50 UTC, bkcsoft commented on gitea/repo_collaborator.go
> +func (c *Client) ListCollaborators(user, repo string) ([]*User, error) {
@tboerger having 100 collaborators isn't large enough? :)

2016-12-20 06:51 UTC, bkcsoft commented on gitea/repo_collaborator.go
> +func (c *Client) ListCollaborators(user, repo string) ([]*User, error) {
and seeing as it's currently locked at 10 entries per call, pagination is required if you have more than that...

2016-12-20 15:19 UTC, tboerger commented on gitea/repo_collaborator.go
> +func (c *Client) ListCollaborators(user, repo string) ([]*User, error) {
100 is nothing for an api ;)

2016-12-21 15:25 UTC, ethantkoenig commented on gitea/repo_collaborator.go
> +func (c *Client) ListCollaborators(user, repo string) ([]*User, error) {
@lunny @bkcsoft @tboerger Do we want pager or not? Happy to add one if we do, just want to make sure.

2016-12-21 15:33 UTC, lunny commented on gitea/repo_collaborator.go
> +func (c *Client) ListCollaborators(user, repo string) ([]*User, error) {
I agree pager is no need currently. But `collaborators := make([]*User, 0, 10)` is really not `collaborators := make([]*User, 10)`.

2016-12-21 16:07 UTC, ethantkoenig commented on gitea/repo_collaborator.go
> +	collaborators := make([]*User, 10)
Fixed.

2016-12-22 00:07 UTC, lunny approved these changes
LGTM

2016-12-22 08:11 UTC, tboerger commented
LGTM

2016-12-22 08:11 UTC, merged