Implement GPG related api
go-gitea/go-sdk pull request #36
Opened 2017-01-17 11:00 UTC by sapk

In order to implement go-gitea/gitea#425

I added all the api call that should be implemented and struct needed to format requests and responses.
 
I follow the github format as a example: https://developer.github.com/v3/users/gpg_keys/

2017-01-17 11:35 UTC, lunny requested changes

2017-01-17 11:35 UTC, lunny commented on gitea/user_gpgkey.go
> +// Copyright 2015 The Gogs Authors. All rights reserved.
error comment head `2017 Gitea`

2017-01-17 11:38 UTC, lunny approved these changes

2017-01-17 11:38 UTC, lunny commented
LGTM

2017-01-17 21:59 UTC, Bwko commented on gitea/user_gpgkey.go
> +	//Verified bool   `json:"verified"`
Nitpicking: Commented code?

2017-01-17 22:03 UTC, sapk commented on gitea/user_gpgkey.go
> +	//Verified bool   `json:"verified"`
It's in the github api format but i don't know if in gitea we should/could present it. Maybe an other solution could be to uncomment it and add omitempty ?

2017-01-17 22:24 UTC, sapk commented
As said on gitter, I hesitate to use PublicGPG... in place of GPG... since it will only contain the public part of the keys like the ssh keys. I don't know what you think of it.

2017-01-18 01:13 UTC, lunny commented
Could we give an option to let user chose and we can use one as default?

2017-01-18 01:26 UTC, sapk commented
@lunny You are saying to let the possibility to users to add a private gpg key to gitea ? From my point of view it would not be a good idea normally you limit the existence of your gpg keys only on trusted media. 

My question was just for the format of object and function name to be as https://github.com/go-gitea/go-sdk/blob/master/gitea/user_key.go#L15 since it's the same case (gitea only need the public key)

2017-01-18 12:43 UTC, Bwko commented
I think that GPG is clear enough, since we don't have the private key

2017-01-18 12:45 UTC, Bwko commented on gitea/user_gpgkey.go
> +	//Verified bool   `json:"verified"`
We could supply it, so you could just uncomment it

2017-01-18 16:32 UTC, sapk commented
Ok perfect i will stick with this to continue in the next part (API and UI) in gitea.

2017-01-18 17:41 UTC, Bwko commented
LGTM

2017-01-21 02:23 UTC, bkcsoft commented
@sapk Is this done?

2017-01-21 02:24 UTC, merged

2017-01-21 02:25 UTC, bkcsoft commented
It follows the [spec](https://developer.github.com/v3/users/gpg_keys/) so I'm merging it anyway 😂