Issue webhook payload
go-gitea/go-sdk pull request #38
Opened 2017-02-11 12:01 UTC by thehowl

This PR prepares for an upcoming pull request on the main repository that aims to implement https://github.com/go-gitea/gitea/issues/132, adding webhook for issue events.

A small API breakage would be introduced in the SDK (though the API JSON objects' structure would remain untouched, if not for some shifting of the position of the fields). As most fields between the PullRequestPayload and the IssuePayload would be the same, the idea is to move the fields to a common BaseIssuePayload, although this would bring a small breakage to when constructing the struct of a PullRequestPayload:

```go
// No longer possible after this PR
pr := &gitea.PullRequestPayload{
	Index: 64, 
}
```

However, accessing the struct fields would still be possible after the struct is initialised.

```go
pr := &gitea.PullRequestPayload{}
pr.Index = 64
_ = pr.Index
```

This would be, however, a very small issue, as the PullRequestPayload is only initialised by Gitea itself ([see this github search](https://github.com/search?utf8=%E2%9C%93&q=code.gitea.io%2Fsdk+PullRequestPayload&type=Code&ref=searchresults)), but Gitea vendors its dependencies anyway, so this would break only in the event of a vendor update with no update to models/issue.go's struct initialisations.

2017-02-11 12:13 UTC, lunny requested changes

2017-02-11 12:13 UTC, lunny commented on gitea/hook.go
> +// Copyright 2017 The Gitea Authors. All rights reserved.
This line is the only need and put it after the first line.

2017-02-11 12:54 UTC, lunny approved these changes

2017-02-11 12:55 UTC, lunny commented
How about use the duplicated struct between `Issue` and `Pull` for the compitable?

2017-02-11 12:57 UTC, thehowl commented
For the computable? I'm sorry, I did not understand. Could you elaborate?

2017-02-11 13:00 UTC, lunny requested changes

2017-02-11 13:00 UTC, lunny commented on gitea/hook.go
> +// JSONPayload FIXME
comment

2017-02-11 13:01 UTC, lunny commented
I mean maybe remove `BaseIssuePayload` and copy the fields to `IssuePayload` and `PullPayload` is better.

2017-02-11 13:44 UTC, thehowl commented
Yeah, that was how I originally thought about doing it (and the safest way, since it doesn't cause any breakage). However, it's a matter of convenience and code de-duplication.

I'm gonna do as you said anyway, mostly because of what @tboerger said on Gitter.

2017-02-11 14:00 UTC, lunny approved these changes

2017-02-11 14:00 UTC, lunny commented
LGTM

2017-02-11 17:18 UTC, thehowl commented
I've changed the HookIssueAction names of the ones I added, and removed the comment ones, to better mimic the GitHub webhooks. Issue comments will come at a later stage (and PR).

2017-02-13 09:13 UTC, tboerger commented
LGTM

2017-02-13 11:50 UTC, merged