Introduce Wiki markdown API option
go-gitea/go-sdk pull request #42
Opened 2017-02-23 08:35 UTC by andrew-boyarshin

As it is in the title.

For go-gitea/gitea#1027.

2017-02-23 09:24 UTC, lunny commented
LGTM

2017-02-23 09:28 UTC, andrew-boyarshin commented
This PR would also require documentation change. For example

Wiki (```"true"```/```"false"```) - render markdown as wiki page. Influences link URLs.

2017-02-23 14:04 UTC, appleboy approved these changes

2017-02-23 14:04 UTC, appleboy commented
LGTM

2017-02-23 22:28 UTC, bkcsoft requested changes

2017-02-23 22:28 UTC, bkcsoft commented on gitea/miscellaneous.go
> +	Wiki    string
This should be a `bool`, not a string

2017-02-24 01:26 UTC, lunny commented on gitea/miscellaneous.go
> +	Wiki    string
indeed

2017-02-24 03:44 UTC, andrew-boyarshin commented
I agree, but there were problems finding documentation. How can I be sure without docs that ```bind``` can bind to non-string fields? Will change.

2017-02-24 04:39 UTC, lunny commented
@andrew-boyarshin what bind?

2017-02-24 09:59 UTC, andrew-boyarshin commented
@lunny macaron one. That binds JSON to ```api.MarkdownOption``` structure.

2017-02-24 14:11 UTC, andrew-boyarshin commented
@bkcsoft time to remove change request?

Pending merge.

2017-02-24 14:28 UTC, tboerger commented
LGTM

2017-02-24 15:00 UTC, merged