duplicated of json field
go-gitea/go-sdk pull request #47
Opened 2017-03-16 08:14 UTC by appleboy

see https://github.com/go-gitea/go-sdk/blob/master/gitea/release.go#L17-L19

2017-03-16 11:11 UTC, tboerger commented
LGTM

2017-03-16 11:33 UTC, lunny commented
Is the change compatible with Github's API?

2017-03-16 12:22 UTC, tboerger commented
> Is the change compatible with Github's API?

Just look some lines above, the JSON field is already taken by the tag name.

2017-04-14 10:22 UTC, sapk commented
As described here https://developer.github.com/v3/repos/releases/. It is TagName that should be rename and not title.

2017-04-14 10:24 UTC, sapk requested changes
As described here https://developer.github.com/v3/repos/releases/. It is TagName that should be rename and not title.

2017-04-14 10:24 UTC, sapk commented on gitea/release.go
>  	TagName      string    `json:"name"`
should be "tag_name"

2017-04-14 10:24 UTC, sapk commented on gitea/release.go
> +	Title        string    `json:"title"`
keep "name" here

2017-04-15 14:54 UTC, appleboy commented
@sapk @lunny @tboerger updated.

2017-04-15 15:49 UTC, sapk commented
First LGTM ^^

2017-04-15 17:46 UTC, strk commented
On Sat, Apr 15, 2017 at 08:49:12AM -0700, Antoine GIRARD wrote:
> First LGTM ^^

Does it mean  you're a maintainer now ? Because I don't see you
yet in the MAINTAINERS file ?

Take my LGTM if yours isn't good (I'm trusting you)

2017-04-15 23:07 UTC, merged

2017-04-15 23:42 UTC, appleboy commented
@sapk Could you update this https://github.com/go-gitea/go-sdk/blob/master/MAINTAINERS file in all repository of Gitea organization？