Improving swagger doc @ Feature/timetracker
go-gitea/go-sdk pull request #69
Opened 2017-08-12 10:29 UTC by JonasFranzDEV

This will change `swagger:response` to `swagger:paramater` as requested by @sapk at https://github.com/go-gitea/gitea/pull/2211#discussion_r131859268.

(Blocks go-gitea/gitea#2211)

2017-08-12 11:52 UTC, sapk requested changes

2017-08-12 11:52 UTC, sapk commented on gitea/issue_tracked_time.go
> +// in: body
// in: body should be over Time (L51)

2017-08-13 00:01 UTC, sapk commented
LGTM

2017-08-13 20:35 UTC, lafriks commented
LGTM

2017-08-13 20:36 UTC, merged